### PR TITLE
Add shellcheck plugin

### PR DESCRIPTION
**Pull request by yhontyk**
> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Adds a vscode-shellcheck plugin in che-docs devfile

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18900

### Specify the version of the product this PR applies to.
Current

### PR Checklist

As the author of this Pull Request I made sure that:

- [x] `vale` has been run successfully against the PR branch
- [x] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by ericwill — APPROVED** [review]

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
@boczkowska you started from an old state of the `master` branch. Think about rebasing this branch in your repository. GitHub UI rebase worked for this branch ;)

**Comment by themr0c** [comment]
Unfortunately, the shellcheck extension does not work :(.

**Comment by themr0c** [comment]
Linkchecker failed on a "connection rest by peer" error. Relaunching the build.

**Comment by yhontyk** [comment]
@themr0c shall I close it? I was confused - it showed up in the settings and command palette for me but the check didn't actually output anything. I thought I was doing smth wrong. :(

**Pull request merged**
