### PR TITLE
Che 7: Securing Che

### PR DESCRIPTION
**Pull request by MichalMaler**
Signed-off-by: Michal Maléř <mmaler@redhat.com>

https://issues.jboss.org/browse/RHDEVDOCS-1149

adding content about Securing Che

rewrote this document into .adoc
https://docs.google.com/document/d/1gvki1dXWtq0Pha4Nv6yAVmuZfVx8U_MIHgv8C59t_3A/edit#

### CODE REVIEW

**Comment by MichalMaler** [comment]
It's ready for SME review @slemeur @l0rd

@rkratky @supriya-bharadwaj Can I ask you for a Peer review?

**Comment by slemeur** [comment]
While those are great description of "how it works", it does not really explain, how an admin must configure Che to run it completely secured. 

Don't take me wrong, this doc is very helpful and should be merged, but target a different purpose. I think we should rethink this one and move it somewhere else.

@rkratky = what would you propose?

**Review by rkratky — CHANGES_REQUESTED** [review]
@MichalMaler Don't commit built HTML files to the repo. In this case, `assembly_securing-che.html`. Please, remove it.

**Review by rkratky — APPROVED** [review]

**Comment by slemeur** [comment]
@rkratky have you seen my comment? I see that merging. But I don't think the content of the document is going to help an admin to configure Che to be secured.

**Pull request merged**
