### PR TITLE
feat: Adapt doc to CheCluster API V2

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

## What does this pull request change
Adopt doc to CheCluster API V2

## What issues does this pull request fix or reference
https://github.com/eclipse/che/issues/20758

## Pull request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Comment by themr0c** [comment]
Please confirm the milestone: 
* next release
* not to backport for Dev Spaces 3.0.

**Comment by tolusha** [comment]
No need to backport to DevSpaces 3.0

**Comment by themr0c** [comment]
@tolusha Is it OK to defer the merge for a few days to have keep a simpler workflow for the backports during that period?

**Comment by tolusha** [comment]
It is ok for me

**Comment by tolusha** [comment]
@themr0c 
Can we merge?

**Review by ibuziuk — APPROVED** [review]

**Review by themr0c — APPROVED** [review]

**Pull request merged**
