### PR TITLE
Common terms capitalisation check

### PR DESCRIPTION
**Pull request by yhontyk**
### What does this PR do?
Adds a vale rule to check common industry names,

### Specify the version of the product this PR applies to.

### CODE REVIEW

**Comment by rkratky** [comment]
I may be misunderstanding how this works, @boczkowska, but I'm concerned a list like this would flag false positives in many places where the substitutions are not desired, e.g. in URLs, command outputs, etc. I'm talking about things like `git`, `docker, `api`, `php`, ...

Also, will the strings only be matched if they are recognized as separate words? If not, strings like `ide` `pod`, or `api` would again lead to false positives.

**Comment by yhontyk** [comment]
@rkratky vale ignores everything that is in codeblocks by default: https://errata-ai.gitbook.io/vale/getting-started/configuration#ignoredscopes-core

**Comment by yhontyk** [comment]
Regarding "pods" - yes, there will be false positives since the capitalization depends on the context. I made the level of this check as `warning`, not an error. There isn't really a way to configure this, unfortunately.

**Comment by yhontyk** [comment]
@rkratky ok, it gives to many false positives indeed. Putting WIP on this PR, will investigate.

**Comment by yhontyk** [comment]
@rkratky @themr0c 
regex to the rescue :D I'm sure there's a smarter way to do it though...

A config to ignore codeblocks, a regex to check only the stuff that starts with a whitespace.
`command openshift` will probably still throw an error, I'll need to think about how to escape that.

Please test. #worksonmycomputer

**Comment by yhontyk** [comment]
The output with all the styles off except this one:

> src/main/pages/che-7/administration-guide/con_machine-token-validation.adoc
>  8:130  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/administration-guide/con_database-setup.adoc
>  38:125  warning  Consider using 'Operator'       CheDocs.CommonTerms 
>                   instead of 'operator'                               
> 
> 
>  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
>  24:22  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
>  33:22  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/administration-guide/proc_checking-important-logs.adoc
>  10:35  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
>  10:75  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
>  46:27  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/administration-guide/proc_developing-grafana-dashboards.adoc
>  32:72  warning  Consider using 'Grafana'        CheDocs.CommonTerms 
>                  instead of 'grafana'                                
> 
> 
>  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
>  16:35  warning  Consider using 'Java' instead   CheDocs.CommonTerms 
>                  of 'java'                                           
> 
> 
>  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
>  5:43  warning  Consider using 'Operator'       CheDocs.CommonTerms 
>                 instead of 'operator'                               
> 
> 
>  src/main/pages/che-7/administration-guide/ref_omnisharp-theia-plug-in.adoc
>  9:28  warning  Consider using '.NET' instead   CheDocs.CommonTerms 
>                 of '.Net'                                           
> 
> 
>  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
>  14:10  warning  Consider using 'GitHub'         CheDocs.CommonTerms 
>                  instead of 'Github'                                 
> 
> 
>  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
>  50:23  warning  Consider using 'URL' instead    CheDocs.CommonTerms 
>                  of 'url'                                            
>  51:48  warning  Consider using 'URL' instead    CheDocs.CommonTerms 
>                  of 'url'                                            
>  53:29  warning  Consider using 'URL' instead    CheDocs.CommonTerms 
>                  of 'url'                                            
> 
> 
>  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
>  22:4   warning  Consider using 'Node.js'        CheDocs.CommonTerms 
>                  instead of 'NodeJS'                                 
>  24:12  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
>  14:9  warning  Consider using 'VS Code'        CheDocs.CommonTerms 
>                 instead of 'VS code'                                
> 
> 
>  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
>  73:51  warning  Consider using 'Git' instead    CheDocs.CommonTerms 
>                  of 'git'                                            
> 
> 
>  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
>  53:4  warning  Consider using 'Node.js'        CheDocs.CommonTerms 
>                 instead of 'NodeJS'                                 
> 
> 
>  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
>  79:139  warning  Consider using 'Node.js'        CheDocs.CommonTerms 
>                   instead of 'NodeJS'                                 
> 
> 
>  src/main/pages/che-7/end-user-guide/proc_managing-git-configuration-identity.adoc
>  38:2  warning  Consider using 'Git' instead    CheDocs.CommonTerms 
>                 of 'git'                                            
> 
> 
>  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
>  29:51  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
>  38:26  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                  of 'pod'                                            
> 
> 
>  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
>  215:63   warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                    of 'pod'                                            
>  321:141  warning  Consider using 'Docker'         CheDocs.CommonTerms 
>                    instead of 'docker'                                 
>  446:39   warning  Consider using 'Docker'         CheDocs.CommonTerms 
>                    instead of 'docker'                                 
>  505:191  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                    of 'pod'                                            
> 
> 
>  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
>  34:4  warning  Consider using 'OpenShift'      CheDocs.CommonTerms 
>                 instead of 'Openshift'                              
> 
> 
>  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
>  22:58  warning  Consider using 'OpenShift'      CheDocs.CommonTerms 
>                  instead of 'Openshift'                              
> 
> 
>  src/main/pages/che-7/extensions/proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc
>  15:159  warning  Consider using 'OpenShift'      CheDocs.CommonTerms 
>                   instead of 'Openshift'                              
> 
> 
>  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
>  128:11  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                   of 'pod'                                            
> 
> 
>  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
>  22:108  warning  Consider using 'Git' instead    CheDocs.CommonTerms 
>                   of 'git'                                            
> 
> 
>  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
>  12:56   warning  Consider using 'Kubernetes'     CheDocs.CommonTerms 
>                   instead of 'kubernetes'                             
>  12:209  warning  Consider using 'Kubernetes'     CheDocs.CommonTerms 
>                   instead of 'kubernetes'                             
> 
> 
>  src/main/pages/che-7/overview/con_workspaces-namespaces-configuration.adoc
>  4:47  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                 of 'pod'                                            
> 
> 
>  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
>  97:116  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                   of 'pod'                                            
> 
> 
>  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
>  80:162  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                   of 'pod'                                            
> 
> 
>  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
>  41:104  warning  Consider using 'Operator'       CheDocs.CommonTerms 
>                   instead of 'operator'                               
> 
> 
>  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
>  469:116  warning  Consider using 'Pod' instead    CheDocs.CommonTerms 
>                    of 'pod'                                            

I looked though the files. No "stupid" false positives (aka in urls or ids).Some might be (as Pod vs pod are context dependant, same with Operator/operator) but this needs to be adressed by a human.

**Review by rkratky — APPROVED** [review]
Thanks, @yhontyk, approving for merging.

**Pull request merged**
