### PR TITLE
Add a note about Factories from URL

### PR DESCRIPTION
**Pull request by ghost**
Since dockerfile recipe type isn't supported on OpenShift and k8s infras, this mechanism of creating Factories works on Docker only

### CODE REVIEW

**Comment by bmicklea** [comment]
Is there an issue to add the ability to put a kube YAML in the repo and achieve the same end result?

**Comment by ghost** [comment]
No, there's no such issue

**Comment by benoitf** [comment]
if SPI is set to be OpenShift/K8s the on-the-fly factory could generate a compliant recipe (and not always try to use dockerfile)

**Comment by bmicklea** [comment]
Created: https://github.com/eclipse/che/issues/9879

**Comment by bmicklea** [comment]
Can you comment on the new issue? Also are you saying this should just
work? Or describing how we should make it work in the future?
-- 

Brad Micklea // Director, Product Management // Developer Tools //
416.707.0792

**Review by slemeur — APPROVED** [review]

**Comment by slemeur** [comment]
We should also mention that chedir is not working on OS/Kubernetes - it's pure Docker infra

**Comment by ghost** [comment]
@slemeur yes, I will push info about Chedir to this branch

**Comment by ghost** [comment]
@bmicklea what @benoitf says is that it is possible but of course not at the moment.

**Pull request merged**
