### PR TITLE
Configuring storage strategies

### PR DESCRIPTION
**Pull request by themr0c**
* Move Configuring storage strategies to the Installation Guide.
* Fix xref pointing to this section.

### CODE REVIEW

**Comment by themr0c** [comment]
As I am just moving some existing content, it is expected that vale checks fail.

**Comment by themr0c** [comment]
Linkchecker fail is also unrelated. Will look at it in another PR.

**Review by yhontyk — APPROVED** [review]
LGTM

**Comment by themr0c** [comment]
Skipping the second review, as this PR  is only moving already existing content.

**Pull request merged**
