### PR TITLE
Update monitoring docs

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Reflect changes in https://github.com/eclipse/che/pull/14727

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14601

### CODE REVIEW

**Review by themr0c — CHANGES_REQUESTED** [review]
The titles of the figures ("The Executors panel 2,3,4" and "The Traces panel 2,3,4") do not make much sense to me. Would it be possible to clarify?

**Comment by skabashnyuk** [comment]
Section Executor contains 19 graphs and section Traces contains 16 graphs. They are grouped by 4 panels just to make consuming easier and not to make huge image with 19/16 graphs on it.

**Comment by themr0c** [comment]
Would "The Executors panel, part 1,2,3,4" make sense then?

**Comment by skabashnyuk** [comment]
>Would "The Executors panel, part 1,2,3,4" make sense then?

Yeh. I can do that

**Review by themr0c — APPROVED** [review]
LGMT

**Comment by themr0c** [comment]
Nice! Thank you @skabashnyuk !

**Pull request merged**
