### PR TITLE
Replace image from che.openshift.io/factory/resources with image from  https://raw.githubusercontent.com/eclipse/che/assets

### LINKED ISSUE #17758: Broken contribute/developer workspace badge for external repos README.md
Readme files in any repo using badges with https://che.openshift.io/factory/resources/factory-contribute.svg image are broken.

image

Note that we give that file as an example in our doc: https://www.eclipse.org/che/docs/che-7/end-user-guide/workspaces-overview/#_including_the_developer_workspace_badge_in_a_readme

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Replace image from che.openshift.io/factory/resources with the image from  https://raw.githubusercontent.com/eclipse/che/assets

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/17758

### Specify the version of the product this PR applies to.
7.19

### PR Checklist

As the author of this Pull Request I made sure that:

- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.constant.ts](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.constant.ts) + [product.json](https://github.com/eclipse/che-dashboard/blob/master/src/assets/branding/product.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by rkratky — APPROVED** [review]
Thanks, @skabashnyuk.

**Comment by benoitf** [comment]
FYI this does not fix the issue at all as links are everywhere (like on several repositories) using that previous image link
so real fix is to fix that broken link first.

Also I'm unsure we should use raw.github.com vs using image from https://www.eclipse.org/che

**Comment by sunix** [comment]
So we have to update, or make PR to every repo using this, ... this is not fair for everyone who already created a badge for their repo
https://github.com/search?p=3&q=https%3A%2F%2Fche.openshift.io%2Ffactory%2Fresources%2Ffactory-contribute.svg&type=Code

**Comment by sunix** [comment]
So we have https://www.eclipse.org/che/contribute.svg now which is much simpler to use, and we don't depend on GitHub

**Pull request merged**
