### PR TITLE
fix: maven procedure update

### PR DESCRIPTION
**Pull request by max-cx**
## What does this pull request change?
Update the Maven-related procedure in response to a review of a customer support case and Nick's proposal.

## What issues does this pull request fix or reference?

https://issues.redhat.com/browse/RHDEVDOCS-4547
https://issues.redhat.com/browse/CRW-3418

## Specify the version of the product this pull request applies to
`main` and cherry-pick to `7.52.x` and `7.53.x`

## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/main/src/constants.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Comment by max-cx** [comment]
@nickboldt, fyi:
 
1.

Upstream: `prod-id-short: che`

Downstream: `:prod-id-short: devspaces`

2.

I initially tried incorporating the following info from your proposal into the Prerequisites:

```
* You are logged into an Openshift cluster.
* ... NOT the `openshift-operators` or `openshift-devspaces` namespaces.
```

But then I thought we can drop it:
- `You are logged into an Openshift cluster` is something that is self-explanatory, as well as inapplicable to the Che instances installed on Kubernetes. I could indeed split it into upstream/downstream examples, but as I just mentioned, this is self-explanatory, so we can avoid unnecessary complexity and effort.
- `NOT the openshift-operators or openshift-devspaces namespaces` can be skipped because I already added the user namespace to both the Prerequisites and every step in the procedure, so it'd be a distraction and an overkill.

WDYT?

**Review by nickboldt — APPROVED** [review]
While we generally avoid using second-person statements in procedures like "you are not" or "you know", this is at least consistent with where we HAVE broken the style guide to use second-person statements.

+1, LGTM

**Comment by nickboldt** [comment]
Given 7.55.x is in progress today, you can probably skip cherrypicking this to 7.53.x and instead pick it to 7.55.x

**Review by svor — APPROVED** [review]

**Review by deerskindoll — APPROVED** [review]
lgtm

**Pull request merged**
