### PR TITLE
fix: Update GitLab configuration page

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

## What does this pull request change
Update GitLab oAuth configuration page.
screenshot-0 0 0 0_4000-2022 06 10-09_27_42

## What issues does this pull request fix or reference
fixes https://github.com/eclipse/che/issues/21435

## Pull request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [x] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Comment by themr0c** [comment]
Is the feature for Che 7.50, or does it work already on Che 7.46?

**Comment by themr0c** [comment]
In the corresponding issue I see:

> We can configure only SAAS or on-premises version with the current oAuth provider.

I believe we should add this information in the docs as well. Something like:

> To enable users to work with a remote Git repository that is hosted using one GitLab instance:

**Comment by vinokurig** [comment]
> Is the feature for Che 7.50, or does it work already on Che 7.46?

It already works since the gitlab oAuth is added

**Review by amisevsk — APPROVED** [review]

**Comment by vinokurig** [comment]
@themr0c
> In the corresponding issue I see:
>
> >We can configure only SAAS or on-premises version with the current oAuth provider.
>
>I believe we should add this information in the docs as well. Something like:
>
> >To enable users to work with a remote Git repository that is hosted using one GitLab instance:

I think from this PR it is clear what to do if admin wants to use the SAAS **OR** onpremises version. I don't think it is a good idea to describe that we doesn't support using both instances as it would only confue the reader.

**Review by themr0c — APPROVED** [review]

**Pull request merged**
