### PR TITLE
I430 fix links

### LINKED ISSUE #430: Broken links and file name inconsistencies
The docs contain a number of links that either Jekyll doesn't resolve at all:

* https://github.com/eclipse/che-docs/blame/master/src/main/pages/developer-guide/assemblies.md#L44 (should be `[workspace API][rest-api]`)
* https://github.com/eclipse/che-docs/blame/master/src/main/pages/workspace-admin/workspaces-troubleshooting.md#L19 (should be `[recipe][recipes]`)
* https://github.com/eclipse/che-docs/blame/master/src/main/pages/setup-openshift/admin-guide.md#L162 (should be `[bootstrapper](what-are-workspaces.html#bootstrapper)`)
* https://github.com/eclipse/che-docs/blame/master/src/main/pages/setup-openshift/kubernetes-admin-guide.md#L167 (should be `[bootstrapper](what-are-workspaces.html#bootstrapper)`)
* https://github.com/eclipse/che-docs/blame/master/src/main/pages/setup-docker/docker-single-user.md#L87 (should be `[Run Che-Server directly](#run-without-cli)`)

or that are invalid:

* https://github.com/eclipse/che-docs/blame/master/src/main/pages/user-guide/commands-ide-macro.md#L115 (should be `[server preview URLs](servers.html#preview-urls)`)
* https://github.com/eclipse/che-docs/blame/master/src/main/pages/user-management/permissions.md#L76 (should be `[stack definition][stacks]`)
* https://github.com/eclipse/che-docs/blame/master/src/main/pages/user-management/permissions.md#L90 (should be `[recipe definition][recipes]`)

Some file names don't correspond to the resulting built HTML file names as specified by Jekyll metadata. These resolve correctly when linked to, but it's inconsistent and confusing when identifying non-resolving links:

* `src/main/pages/developer-guide/installers.md` -> `custom-installers.md`
* `src/main/pages/developer-guide/language_servers.md` -> `language-servers.md`
* `src/main/pages/developer-guide/server-side-extension.md` -> `server-side-extensions.md`
* `src/main/pages/spi/spi.md` -> `spi_overview.md`

Plus, there's one link that uses a Google-search redirect URL instead of the resulting URL:

* https://github.com/eclipse/che-docs/blame/master/src/main/pages/dev_essentials/guice.md#L16 (should link to https://github.com/google/guice)

### PR DESCRIPTION
**Pull request by rkratky**
### What does this PR do?

Fixes a number of broken links and inconsistencies. See #430 for details.

### What issues does this PR fix or reference?

Fixes #430.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by rkratky** [comment]
@eivantsov, apologies, I have only now read the Eclipse contribution guidelines -- so these commits are not properly signed-off on. Should I submit a new PR with proper commit messages?

**Comment by ghost** [comment]
I think it's ok to edit the initial commit.

**Comment by ghost** [comment]
@rkratky thanks. Merged.

**Comment by slemeur** [comment]
Thanks @rkratky for the PR.

**Pull request merged**
