### PR TITLE
Asciidoc conversion

### PR DESCRIPTION
**Pull request by rkratky**
### What does this PR do?

Converts the entire bulk of docs from Markdown to Asciidoc(tor). The linked issue (#425) contains detailed explanation and reasoning for the conversion.

Jekyll is still used to generate the site, and the site's design and navigation elements are unchanged. I viewed every single page on the site to check for problems. If you find any, I'll fix them.

The PR includes:

- converted docs source files
- various fixes necessitated by invalid Markdown syntax
- updated Jekyll build system (`run.sh`, `_config.yml`, `Gemfile`)
- Dockerfile for building the image for local building & serving of the site (the image has also been pushed to Docker Hub, so no local building of the image is required; the `run.sh` script pulls this new image)

_The only (quite minor) change is the syntax highlighter used for source-code listings. I couldn't get the currently used one (Rouge) to work, so I used a different one (Coderay). Syntax is still properly highlighted, only the colors used are a tiny bit different._

### What issues does this PR fix or reference?

#425 (Convert docs to AsciiDoc)

### CODE REVIEW

**Comment by ghost** [comment]
@rkratky I can't find pom.xml in the PR - have you changed Docker image here too? https://github.com/eclipse/che-docs/blob/master/pom.xml#L68

**Comment by rkratky** [comment]
@eivantsov 
> I can't find pom.xml in the PR - have you changed Docker image here too? https://github.com/eclipse/che-docs/blob/master/pom.xml#L68

That I forgot. I will fix that. (What is it used for?)

**Comment by rkratky** [comment]
Apologies for the repeated push -- I keep forgetting to sign off on commits.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Well, this is a maven project, and docs are packaged as war artifact that is then packaged into Che server.

**Comment by slemeur** [comment]
+1 for the pom.xml

**Comment by rkratky** [comment]
Thanks, I updated `pom.xml`.

**Review by slemeur — APPROVED** [review]

**Comment by ghost** [comment]
@rkratky can you please resolve conflicts and merge asap?

**Comment by rkratky** [comment]
@eivantsov Apologies for the delay, I was on PTO.

The conflicts are resolved, please merge.

**Pull request merged**
