### PR TITLE
fix che-docs factory URL

### PR DESCRIPTION
**Pull request by themr0c**
fix che-docs factory URL

### CODE REVIEW

**Comment by ibuziuk** [comment]
@themr0c have you verified this on Hosted Che? does all the docs use-cases work as expected?

**Comment by themr0c** [comment]
On Hosted Che:

- It loads with Ephemeral mode set to true.
- Task 'build che-docs (plugin)' has exited with code 0.
- The task “serve che-docs” is running OK, but redirection to http://0.0.0.0:4000 makes the service unusable.

**Comment by ibuziuk** [comment]
@themr0c should work also with PVC based workspaces. Could you create a separate issue for `serve che-docs` command?

**Comment by themr0c** [comment]
[dogfooding] wrong redirection in serve che-docs task:  https://github.com/eclipse/che/issues/15865

Maybe we can merge this PR right now?

**Review by slemeur — APPROVED** [review]

**Pull request merged**
