### PR TITLE
A new procedure + fixes

### PR DESCRIPTION
**Pull request by MichalMaler**
Signed-off-by: Michal Maléř <mmaler@redhat.com>

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?

Documents how to change the plugin registry via preferences

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19237

### Specify the version of the product this PR applies to.

Current master; crw 2.7

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [ ] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by yhontyk — APPROVED** [review]

**Comment by vinokurig** [comment]
Actually there is one more way to add a new pluign-registry url: by executing the `Add Registry` command. I think this should be mentioned as well.

**Review by yhontyk — APPROVED** [review]

**Comment by MichalMaler** [comment]
> Actually there is one more way to add a new pluign-registry url: by executing the `Add Registry` command. I think this should be mentioned as well.

I mention this in the last sentence:
`This check is also functional for plug-ins added using the Command palette command `Add plugin registry`.`

**Comment by vinokurig** [comment]
@MichalMaler We have two ways of adding a plugin-registry URL
* Add via the command
* Add or edit via the `settings.json` file

The first way is more user friendly, because it uses input messages, but it doesn't allow to edit URLs.
The second way is not so user friendly because it is just a JSON file where user have to find a proper place and set an item in the required format, but it gives an ability to edit the items.
So as the topic name sounds as `Adding a custom plug-in registry ...` I think it would be better to describe the first way as a main way to add a registry URL, and then add that if you want to edit entered item you can use the second way.  WDYT?

**Comment by MichalMaler** [comment]
> @MichalMaler We have two ways of adding a plugin-registry URL
> 
> * Add via the command
> * Add or edit via the `settings.json` file
> 
> The first way is more user friendly, because it uses input messages, but it doesn't allow to edit URLs.
> The second way is not so user friendly because it is just a JSON file where user have to find a proper place and set an item in the required format, but it gives an ability to edit the items.
> So as the topic name sounds as `Adding a custom plug-in registry ...` I think it would be better to describe the first way as a main way to add a registry URL, and then add that if you want to edit entered item you can use the second way. WDYT?

Ok, will redo it tomorrow. I am on sick day today. Will get back to you.

**Comment by vinokurig** [comment]
@MichalMaler Get well soon

**Review by vinokurig — APPROVED** [review]

**Pull request merged**
