### PR TITLE
WIP: missing unit

### PR DESCRIPTION
**Pull request by MichalMaler**
Signed-off-by: Michal Maléř <mmaler@redhat.com>

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been configured on the docs side):
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by l0rd — APPROVED** [review]
LGTM

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
Yes but ... that won't work.

This file is generated at build time.

The file committed in che-docs is *not* used for the publication. That counts for upstream as well as for downstream.

That's timely feeding my point about che server parameters documentation automation  leading us to troubles and unnecessary complexity. See: https://github.com/eclipse/che/issues/19630

The right place to edit is
* either directly in the che repository, and then backport to the right branch there. che.properties or multiuser.properties file.
* or the script in che-docs (for quickfixes, while waiting for changes to happen in che repository).

**Comment by MichalMaler** [comment]
@themr0c Yes, thats what I wanted to check with developers, but it seems they have a bank holiday in Ukraine today :) Or something.

Please, can you apply this little change to the che repo file from which this table is generated?

**Review by skabashnyuk — APPROVED** [review]

**Comment by MichalMaler** [comment]
Fixed in Che repo by
https://github.com/eclipse/che/pull/19748#pullrequestreview-652104069

**Pull request merged**
