### PR TITLE
I545 remove rn

### LINKED ISSUE #545: Remove 'release-notes' dir from Jekyll structure
The https://github.com/eclipse/che-docs/tree/master/src/main/pages/release-notes directory (and its contents) serves no purpose in the Jekyll structure as it's not being published on eclipse.org/che/docs/. It should be removed (or possibly moved to the root of the repo to serve as the collection point for RTN published at che.eclipse.org.

### PR DESCRIPTION
**Pull request by rkratky**
### What does this PR do?

* Removes old, unused RN dir. from Jekyll dir. structure.
* Adds new RN dir. with a RN template file to repo root.

### What issues does this PR fix or reference?

Fixes #545.

### CODE REVIEW

**Comment by rkratky** [comment]
@dneary, have a look, please.

**Comment by dneary** [comment]
Apologies - missed the @ message. Can you explain what the I545 stands for at the start of the commit message? Reviewing change now (but I have no rights on the repo).

**Comment by dneary** [comment]
In the release notes blogs, we have some boilerplate which I would like to keep. Is your intention that the release notes files in the repo would be the "meat", rather than being the same as the blog post?

The boilerplate is below. I'd be happy to add it to the file once this commit is approved, or have you add it now. Which do you prefer?


# Eclipse Che $VERSION Release Notes

## $HIGHLIGHT1 $HIGHLIGHT2 $HIGHLIGHT3

Intro paragraph

---

## Quick Start

Che is a cloud IDE and containerized workspace server - get started on:

* Kubernetes ([single-user](https://www.eclipse.org/che/docs/kubernetes-single-user.html) or [multi-user](https://www.eclipse.org/che/docs/kubernetes-multi-user.html))
* OpenShift ([single-user](https://www.eclipse.org/che/docs/openshift-single-user.html) or [multi-user](https://www.eclipse.org/che/docs/openshift-multi-user.html))
* Docker ([single-user](https://www.eclipse.org/che/docs/docker-single-user.html) or [multi-user](https://www.eclipse.org/che/docs/docker-multi-user.html))
* Try Eclipse Che live at [https://che.openshift.io](https://che.openshift.io)

Learn more in our [documentation](https://www.eclipse.org/che/docs/infra-support.html) and start using a shared Che server or local instance today.

---

## $HIGHLIGHT1

Screenshot/illustration

Description

Links to PRs

---

## N Improvements

The Che team has made over 130 changes in the $RELEASE release, touching every part of the project. It is difficult to do them justice here, you can read [the full ChangeLog](https://github.com/eclipse/che/blob/master/CHANGELOG.md#6130-2018-10-24) in the project's source code repository.

---

## Contributing

The Eclipse Che project is always looking for user feedback and new contributors! Find out how you can get involved and help make Che even better.

## Getting involved

You can reach the Eclipse Che community in a number of ways:

* Create an issue in the [Eclipse Che GitHub repository](https://github.com/eclipse/che/)
* Send an email to the [che-dev mailing list](https://accounts.eclipse.org/mailing-list/che-dev) at eclipse.org
* Join us on [the eclipse-che channel on mattermost.eclipse.org](https://mattermost.eclipse.org/eclipse/channels/eclipse-che) to chat in real-time
* Follow us on Twitter [@eclipse_che](https://twitter.com/eclipse_che)

**Comment by slemeur** [comment]
@dneary What the "Contributing" section is linking to? I don't see any links, references that are allowing to do what the paragraph is mentioning. I'd merge "Contributing" and "Getting involved". 

I'd like to keep a section for the "Community Thank you" where contributions from non-contributors are being made.

I'd like to also keep the section about the most noticeable bug fixes.

**Comment by dneary** [comment]
Happy with both of your suggestions. "Contribute to community" links to https://github.com/eclipse/che/blob/master/CONTRIBUTING.md

**Comment by rkratky** [comment]
@dneary 

>  Can you explain what the I545 stands for at the start of the commit message?

Refers to the https://github.com/eclipse/che-docs/issues/545 issue filed for this thing :)

> In the release notes blogs, we have some boilerplate which I would like to keep. Is your intention that the release notes files in the repo would be the "meat", rather than being the same as the blog post?

Not sure what 'meat' means in this context. The idea is to use whatever template you would want the RN to be based on. RN items would be committed to/collected in this repo and subsequently published (copy & paste) on the eclipse.org website.

> The boilerplate is below. I'd be happy to add it to the file once this commit is approved, or have you add it now. Which do you prefer?

Either way works. However, I see you want to make changes to the template based on Stevan's comment, so I suggest I merge this PR and you raise a new one with the right template.

**Comment by dneary** [comment]
OK, I can do that. +1 for getting a template into the repo.

**Comment by rkratky** [comment]
@dneary, @eivantsov, this is ready to be merged; please, approve.

**Comment by dneary** [comment]
I'm not a committer, you need someone else to approve.

**Review by slemeur — APPROVED** [review]

**Pull request merged**
