### PR TITLE
This update address PR 434 and fixes wording, grammar and punctuation errors. The change…

### PR DESCRIPTION
**Pull request by petra-sargent**
…s are in How It Works, What Can Be Configured? and HTTPS Mode

### What does this PR do?
This PR updates the wording to make more clear. 

### What issues does this PR fix or reference?
434

### CODE REVIEW

**Review by slemeur — APPROVED** [review]
Cool ! Thanks @petra-sargent !

**Comment by slemeur** [comment]
@petra-sargent : Before we can merge your PR, we need you to sign the Eclipse Contributor Licence Agreement. Have you got one ? If you have not yet signed it, you can check the [following page](https://github.com/eclipse/che/wiki/Contributor-License-Agreement)
Also, we'll need your commit to be signed-off.

[More info](https://github.com/eclipse/che/wiki/How-To-Contribute#fix-bugs-or-make-enhancements)

Once the CLA is valid, will merge the PR asap.

Let us know if you need any assistance.

**Review by ghost — APPROVED** [review]

**Comment by petra-sargent** [comment]
@slemeur, I verified that I signed the Eclipse Contributor License Agreement.

**Comment by slemeur** [comment]
Perfect ! LGTM :)

**Pull request merged**
