### PR TITLE
Move Customizing the registries back to the Administration Guide

### PR DESCRIPTION
**Pull request by themr0c**
* Move Customizing the registries back to the Administration Guide
* First pass on modularization. Controlled impact on the Installing and Upgrading in restricted environments stories.

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [ ] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Comment by nickboldt** [comment]
Just skimmed this PR... does it include any fixes to the inconsistencies in downstream where for one registry we say to use `docker build` and for the other we say to run `build.sh` ? If not, please consider adding a fix to this PR so that BOTH registries are build with their respective build.sh script, which wraps docker (or podman) and supports flags that make it easier to run in online/offline modes. (It's better UX!)

**Comment by themr0c** [comment]
@nickboldt That's exactly the idea. This PR is the first step to fix stuff downstream and reuse upstream as much as possible.

**Comment by themr0c** [comment]
@nickboldt using build.sh: it has already been fixed, nothing new in this PR. What is new is to reintegrate it in the Administration Guide and make the necessary to reuse most of it downstream.

**Comment by nickboldt** [comment]
> nothing new in this PR

ok, great!

**Review by yhontyk — APPROVED** [review]

**Review by rkratky — APPROVED** [review]

**Pull request merged**
