### PR TITLE
Use eclipse-che as default namespace

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Use `eclipse-che` as a default namespace instead of `che`

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Comment by tolusha** [comment]
`chectl` currently deploys Eclipse Che in a new default namespace `eclipse-che`
This PR replace all references from `che` to `eclipse-che`.
My concerns is the following: when users use commands from the doc for Eclipse Che deployed in a previous default namespace (`che`) they will fail. Basically because all commands use flag `-n eclipse-che`.

**Comment by tolusha** [comment]
Also this PR should be ported to CRW 2.6 doc with
`prod-namespace: openshift-workspaces`

**Comment by MichalMaler** [comment]
Fantastic job,  @tolusha  Anatolii! Let me look at those files if I can fix something that will catch my attention.

**Comment by MichalMaler** [comment]
@tolusha Please, accept my review: https://github.com/tolusha/che-docs/pull/3
We can merge then.
Is this only for the current che master or we need to get this into the CRW 2.5 docs as well?

**Comment by themr0c** [comment]
(Updated the branch from GitHub UI to revalidate links)

**Review by MichalMaler — APPROVED** [review]

**Pull request merged**
