### PR TITLE
Fix #377 Update che addon remove steps for minishift.

### LINKED ISSUE #377: Update che addon remove step for minishift
Currently, minishift section https://www.eclipse.org/che/docs/6/che/docs/openshift-single-user.html#minishift (addon-remove subsection) it has following details which need to be updated.

```
minishift addons remove \
--addon-env OPENSHIFT_TOKEN="" \
--addon-env CHE_DOCKER_IMAGE="" \
--addon-env GITHUB_CLIENT_ID="" \
--addon-env GITHUB_CLIENT_SECRET="" \
--addon-env NAMESPACE=mini-che che
```

It should be updated to since we made changes from minishift addon command options and remove now doesn't need metadata if it is not required for .addon.remove file.

```
minishift addons remove che
```

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by slemeur — APPROVED** [review]

**Comment by slemeur** [comment]
LGTM

**Comment by bmicklea** [comment]
@praveenkumar please add your eclipse committer credentials then we'll merge.

**Comment by bmicklea** [comment]
Signed-off-by: Brad Micklea <bmicklea@redhat.com>

**Review by bmicklea — APPROVED** [review]
I'll take responsibility for the commit.

**Pull request merged**
