### PR TITLE
Removing the statement that external db requires external keycloak setup

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Removing the statement that external db requires external keycloak setup

### What issues does this PR fix or reference?
N/A

### Specify the version of the product this PR applies to. 
7.x

### CODE REVIEW

**Comment by ibuziuk** [comment]
@tolusha @davidfestal could you please review?

**Comment by dmytro-ndp** [comment]
@ibuziuk: it's not possible to install CRW 2.1 (based on Eclipse Che 7.9.x) with external DB and provided identity provider. I am curious If it is now possible to do in newer versions of Eclipse Che.

**Comment by ibuziuk** [comment]
well, if it is the case I do not understand how come DB and keycloak are related? If it is true and external db require external keycloak for some reason this should be well documented and explained

**Comment by ibuziuk** [comment]
@davidfestal could you please comment?

**Comment by yhontyk** [comment]
@ibuziuk @dmytro-ndp @davidfestal any updates on this PR? 
Should I merge it or should we keep the sentence and add more documentation about it?

**Comment by ibuziuk** [comment]
Related issue - https://github.com/eclipse/che/issues/17274
I believe merging this PR is blocked by the issue above ^

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che-docs/pull/1430

**Pull request closed without merging**
