### PR TITLE
enhancement: a workspace example in snip

### PR DESCRIPTION
**Pull request by MichalMaler**
Signed-off-by: Michal Maléř <mmaler@redhat.com>

https://issues.redhat.com/browse/RHDEVDOCS-3187

## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by nickboldt** [comment]
stated goal in the JIRA is "Replace reference to unofficial sample code in Admin Guide w/ crw-samples" ... yet this is a che-sample you're including in this PR. How will this be downstreamed to a CRW sample from https://github.com/redhat-developer/codeready-workspaces-images/tree/crw-2-rhel-8/codeready-workspaces-devfileregistry/devfiles ?

For example why not use https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml ?

**Review by svor — APPROVED** [review]

**Comment by MichalMaler** [comment]
> stated goal in the JIRA is "Replace reference to unofficial sample code in Admin Guide w/ crw-samples" ... yet this is a che-sample you're including in this PR. How will this be downstreamed to a CRW sample from https://github.com/redhat-developer/codeready-workspaces-images/tree/crw-2-rhel-8/codeready-workspaces-devfileregistry/devfiles ?
> 
> For example why not use https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml ?

Nick, this is purely for Che. I will put the CRW equivalent in the CRW repo so that we will have identical docs but separate example snip files with different yamls.

**Comment by MichalMaler** [comment]
Here is the MR for the synergy with CRW
https://gitlab.cee.redhat.com/red-hat-developers-documentation/red-hat-devtools/-/merge_requests/1333

Will apply Nick's comments about the version.

**Review by svor — COMMENTED** [review]
```
CodeReady Workspaces is applying the defaults for the kubernetes component type: a memory limit of 1 GiB and a memory request of 512 MiB. This is because the kubernetes component references a Deployment manifest that has a container specification with no resource limits or requests.
```
should be replaced with
```
CodeReady Workspaces is applying the defaults for the dockerimage component type: a memory limit of 1 GiB and a memory request of 512 MiB.
```

**Review by svor — COMMENTED** [review]
Memory request for machine exec should be 32MiB (not 128): https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L123. So, the total value of memory request should be changed to 1.38 GiB

**Pull request merged**
