### PR TITLE
Che4z install guide improvement

### PR DESCRIPTION
**Pull request by DStatWriter**
### What does this PR do?
Expands install section replacing original link to separate page

### What issues does this PR fix or reference?
#15011

### CODE REVIEW

**Comment by DStatWriter** [comment]
This was resubmitted from scratch, including the amended code with all improvements applied, and the "signed off" footer. I am unaware of any reason why the checks should now fail

**Comment by themr0c** [comment]
Hi @DStatWriter unfortunately, only the last commit has the signoff, you should squash all the commits, it will be easier to manage on one single commit.

**Comment by DStatWriter** [comment]
> Hi @DStatWriter unfortunately, only the last commit has the sign-off, you should squash all the commits, it will be easier to manage on one single commit.

Hi @themr0c, what i don't understand is this:
I closed the previous PR's
I made a new branch
I copied and applied the suggested code as it was after all commits were applied
I then added the footer and opened as a new issue then new PR

However, it still shows this issue? How can it show several commits when i submitted it as a single commit in a new branch?

I appreciate this may be frustrating for all concerned, but i can only re-state, that neither Zeb or myself are coders, we are writers, and we are finding this process nigh on impossible to navigate.

**Comment by DStatWriter** [comment]
closed and re-submitted

**Pull request closed without merging**
