### PR TITLE
feat(troubleshooting): Add section about slow workspaces

### LINKED ISSUE #17308: Add a doc section about how to troubleshoot slow workspaces
### Is your enhancement related to a problem? Please describe.

We often get complaints about slowness of workspaces: [at startup](https://github.com/eclipse/che/issues/14879) and at runtime. There are some tips & tricks to make them faster that should be shared in the documentation.

### Describe the solution you'd like

In the "Troubleshooting for end-users guide" I would add the following sections:

1. Improve Workspaces Startup Times
- Image puller
- Change storage backend or configure ephemeral mode
- Offline setup
- Reduce the number of plugins
- Reduce the number of public routes
- CDN configuration

2. Improve Workspace Runtime Performances
- Increasing CPU
- Increase memory
- Change storage backend or configure ephemeral mode

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
troubleshooting about slow workspaces :
- slow startup
- poor performances at runtime

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/17308

### Specify the version of the product this PR applies to. 
7.16+

Change-Id: I06b5d0f7d19f32d6860245771e5a02ff9c4867c1
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
https://che.openshift.io/factory/?url=https://github.com/benoitf/che-docs/tree/CHE-17308

**Review by rkratky — APPROVED** [review]
Thanks, @benoitf. I committed some lang. and mark-up fixes (and fixed the merge conflict). Apologies, for some reason, the changes against your orig. version are not shown even though I used `git mv` for renaming. Not sure what happened. If you're OK with the suggested changes, we can merge.

**Comment by rkratky** [comment]
Oh, I see you're on PTO, @benoitf. I'm going to merge now, and if there are problems with my modifications, I'll revisit it.

**Comment by benoitf** [comment]
yes I'm on PTO. You can change everything :-)

**Review by benoitf — COMMENTED** [review]
changes look perfect for me :+1:

**Comment by rkratky** [comment]
Shoo, go away, you're not supposed to be here! :-D

**Pull request merged**
