### PR TITLE
chore(netlify): Allow to deploy each PR to netlify and add result in PR status

### PR DESCRIPTION
**Pull request by benoitf**
> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
build with github action and then deploy it remotely to netlify

Display link in PR status:
image

### What issues does this PR fix or reference?
N/A

### Specify the version of the product this PR applies to.
N/A

### PR Checklist

As the author of this Pull Request I made sure that:

- [x] `vale` has been run successufully against the PR branch
- [x] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.constant.ts](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.constant.ts) + [product.json](https://github.com/eclipse/che-dashboard/blob/master/src/assets/branding/product.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

Change-Id: I90f9770a50b53bcc01c1e8739324c88c3f6c356a
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
Awesome. I like it!

**Comment by benoitf** [comment]
I need to know if it is working on forks or not (if credentials are propagated or not)

**Comment by rkratky** [comment]
@benoitf, the netlify step is now failing (see, e.g. https://github.com/eclipse/che-docs/pull/1584/checks?check_run_id=1117868886), which is blocking PRs. Triggering the build again doesn't help. The build itself is not an issue -- see the log.

I haven't had time to investigate further, but until it's resolved, we may need to revert this.

**Comment by benoitf** [comment]
@rkratky I will investigate the issue. I think it's related to missing secrets on forks

AFAIK it's not really "blocking" the PR as you can still merge as it's not a required/mandatory check.
But in the meantime I'm ok if you revert also

**Comment by benoitf** [comment]
@rkratky it should be fixed now

**Comment by rkratky** [comment]
@benoitf 

> AFAIK it's not really "blocking" the PR as you can still merge as it's not a required/mandatory check.

Right, thanks. I didn't realize that.

>  it should be fixed now

I'm still seeing the "Publish" step taking too long and timing out.

**Comment by benoitf** [comment]
@rkratky maybe there is a need of rebasing or updating the PR
because gihub actions are triggered again only if there is a change in codebase ?

do you have an example where you see this step on new PR ?

**Comment by rkratky** [comment]
I tried by clicking "Re-run all jobs" in Netlify. But I see a new PR was published fine, so you're pbbly right.

**Comment by benoitf** [comment]
yep I think these one need a rebase

**Pull request merged**
