### PR TITLE
Update che_7_docs to include Explorer for Endevor.yml

### PR DESCRIPTION
**Pull request by DStatWriter**
Che4z Doc:
Adds Explorer for Endevor to Extensions menu with links to docs.

Signed-off-by: Daniel Statham <Daniel.Statham@Broadcom.com>

### What does this PR do?
Adds sidebar entry for Explorer for Endevor, with links to documents
Adds documents to repo

### What issues does this PR fix or reference?
#15246 #15199

### CODE REVIEW

**Comment by DStatWriter** [comment]
Docs added, please review

**Comment by DStatWriter** [comment]
Hi all, can this be reviewed while we wait for the code to clear legal so i can have it ready to go please?

**Comment by rkratky** [comment]
Apologies, @DStatWriter. It's a mouthful, and we've been busy with releases :) Could you please convert the mark-up to AsciiDoc?

**Comment by DStatWriter** [comment]
> Apologies, @DStatWriter. It's a mouthful, and we've been busy with releases :) Could you please convert the mark-up to AsciiDoc?

Hey @rkratky, I have now converted to AsciiDoc if you could take a look please.

Thanks,

Dan

**Comment by themr0c** [comment]
Here are some language improvements hints (by write-good):

```
for file in `find  src/main/pages/che-7/extensions/ -name 'E4E-*.adoc'` ; do ./node_modules/.bin/write-good $file ; done
In src/main/pages/che-7/extensions/E4E-TPSA.adoc
=============
y software licences that are described in the following table. To read each comp
                         ^^^^^^^^^^^^^
"are described" may be passive voice on line 3 at column 75
In src/main/pages/che-7/extensions/E4E-Hosts.adoc
=============
 support the creation of multiple hosts in one instance.
                         ^^^^^^^^
"multiple" is wordy or unneeded on line 3 at column 121
-------------
 host per project or per time period, if working with a single data source.
                         ^^^^^^^^^^^
"time period" is wordy or unneeded on line 7 at column 37
-------------
* Use several hosts for one project, drawing from one data source each.
      ^^^^^^^
"several" is a weasel word on line 8 at column 6
-------------
* Once a host is created, you can then refresh, update, or delete it as required
              ^^^^^^^^^^
"is created" may be passive voice on line 9 at column 14
-------------
Minimize the other tabs in Visual Studio Code if needed
^^^^^^^^
"Minimize" is wordy or unneeded on line 18 at column 0
-------------
You will be prompted to enter a z/OS URL in the format 'http(s)://url:port', for
         ^^^^^^^^^^^
"be prompted" may be passive voice on line 20 at column 9
-------------
 repository name and URL are accepted, the CA Endevor SCM configuration becomes 
                         ^^^^^^^^^^^^
"are accepted" may be passive voice on line 23 at column 31
-------------
You have successfully created a new Host connected to a repository, and the Host
         ^^^^^^^^^^^^
"successfully" can weaken meaning on line 26 at column 9
-------------
repository, and the Host is listed under Explorer for Endevor in the Visual Stud
                         ^^^^^^^^^
"is listed" may be passive voice on line 26 at column 81
-------------
udio Code shows all your currently mapped Explorer for Endevor Hosts. +
                         ^^^^^^^^^
"currently" can weaken meaning on line 30 at column 66
-------------
The filter is highlighted, and the following icons are displayed:
           ^^^^^^^^^^^^^^
"is highlighted" may be passive voice on line 38 at column 11
-------------
 and the following icons are displayed:
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 38 at column 51
-------------
The Host has been refreshed
             ^^^^^^^^^^^^^^
"been refreshed" may be passive voice on line 47 at column 13
-------------
NOTE: You cannot currently update the URL of the data source, or the selected En
                 ^^^^^^^^^
"currently" can weaken meaning on line 53 at column 17
-------------
devor Your current Hosts are displayed under the Explorer for Endevor tab in the
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 57 at column 54
-------------
The host is highlighted, and the following icons are displayed:
         ^^^^^^^^^^^^^^
"is highlighted" may be passive voice on line 60 at column 9
-------------
 and the following icons are displayed:
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 60 at column 49
-------------
 following error message is displayed: +
                         ^^^^^^^^^^^^
"is displayed" may be passive voice on line 70 at column 127
-------------
 and the Data Source URL are shown for reference only
                         ^^^^^^^^^
"are shown" may be passive voice on line 81 at column 56
-------------
 are shown for reference only
                         ^^^^
"only" can weaken meaning on line 81 at column 80
-------------
The changes are reflected in the Explorer for Endevor tab
            ^^^^^^^^^^^^^
"are reflected" may be passive voice on line 85 at column 12
-------------
The Host has been updated.
             ^^^^^^^^^^^^
"been updated" may be passive voice on line 87 at column 13
-------------
You may add several hosts for each project in Explorer for Endevor, and as such,
            ^^^^^^^
"several" is a weasel word on line 91 at column 12
-------------
h, the list of Hosts can quickly become unmanageable.
                         ^^^^^^^
"quickly" can weaken meaning on line 91 at column 103
-------------
reference point, you can easily delete redundant Hosts from the Explorer for End
                         ^^^^^^
"easily" can weaken meaning on line 93 at column 51
-------------
The Host is highlighted, and the following icons are displayed:
         ^^^^^^^^^^^^^^
"is highlighted" may be passive voice on line 99 at column 9
-------------
 and the following icons are displayed:
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 99 at column 49
-------------
The host is deleted and has been removed from the list in the Explorer for Endev
         ^^^^^^^^^^
"is deleted" may be passive voice on line 114 at column 9
-------------
 host is deleted and has been removed from the list in the Explorer for Endevor 
                         ^^^^^^^^^^^^
"been removed" may be passive voice on line 114 at column 28
In src/main/pages/che-7/extensions/E4E-Accessibility.adoc
=============
Broadcom is committed to addressing user accessibility in the development of its
         ^^^^^^^^^^^^
"is committed" may be passive voice on line 3 at column 9
-------------
egardless of ability, to accomplish vital business tasks.
                         ^^^^^^^^^^
"accomplish" is wordy or unneeded on line 3 at column 157
-------------
cursor easier to find or minimize its blinking
                         ^^^^^^^^
"minimize" is wordy or unneeded on line 18 at column 81
-------------
n accessibility features are turned on or off.
                         ^^^^^^^^^^
"are turned" may be passive voice on line 40 at column 61
-------------
Defines how quickly a character repeats when a key is struck.
            ^^^^^^^
"quickly" can weaken meaning on line 53 at column 12
-------------
acter repeats when a key is struck.
                         ^^^^^^^^^
"is struck" may be passive voice on line 53 at column 51
-------------
active until another key is pressed.
                         ^^^^^^^^^^
"is pressed" may be passive voice on line 59 at column 152
In src/main/pages/che-7/extensions/E4E-ReleaseNotes.adoc
=============
Version 0.8 was released on 1 August 2019 and includes the following features:
            ^^^^^^^^^^^^
"was released" may be passive voice on line 4 at column 12
-------------
Version 0.9 was released on 19 September 2019 and includes the following feature
            ^^^^^^^^^^^^
"was released" may be passive voice on line 16 at column 12
In src/main/pages/che-7/extensions/E4E-Actions.adoc
=============
The created filters are derived from the properties of the specified element.
                    ^^^^^^^^^^^
"are derived" may be passive voice on line 9 at column 20
-------------
As such, they can be used, with wildcards, to identify other elements of similar
                  ^^^^^^^
"be used" may be passive voice on line 10 at column 18
-------------
Filters can be created in two ways. You can create a filter manually by entering
            ^^^^^^^^^^
"be created" may be passive voice on line 14 at column 12
-------------
f the parameters (with a maximum of two parameters as * wildcards) are correctly
                         ^^^^^^^
"maximum" is wordy or unneeded on line 30 at column 26
-------------
ters as * wildcards) are correctly entered, the filter will appear under the exp
                         ^^^^^^^^^
"correctly" can weaken meaning on line 30 at column 72
-------------
arches for elements with closely matching characteristics elsewhere in the data 
                         ^^^^^^^
"closely" can weaken meaning on line 55 at column 74
-------------
The filter is highlighted, and the following options are displayed: +
           ^^^^^^^^^^^^^^
"is highlighted" may be passive voice on line 60 at column 11
-------------
nd the following options are displayed: +
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 60 at column 53
-------------
The following message is displayed: +
                      ^^^^^^^^^^^^
"is displayed" may be passive voice on line 66 at column 22
-------------
The selected filter is highlighted with only the Element field as a Wildcard ( *
                    ^^^^^^^^^^^^^^
"is highlighted" may be passive voice on line 70 at column 20
-------------
lter is highlighted with only the Element field as a Wildcard ( * ):
                         ^^^^
"only" can weaken meaning on line 70 at column 40
-------------
This filter could now be used, for example, to display all Types and Elements in
                      ^^^^^^^
"be used" may be passive voice on line 80 at column 22
-------------
The filter has been edited and now shows under the list of saved filters. +
               ^^^^^^^^^^^
"been edited" may be passive voice on line 84 at column 15
-------------
ed if you are conducting several different searches. To address this, delete fil
                         ^^^^^^^
"several" is a weasel word on line 86 at column 144
-------------
es or specific data must be entered for every level when a filter is edited
                         ^^^^^^^^^^
"be entered" may be passive voice on line 89 at column 41
-------------
very level when a filter is edited
                         ^^^^^^^^^
"is edited" may be passive voice on line 89 at column 82
-------------
* You can key several fields as wildcards, however ensure that you use no more t
              ^^^^^^^
"several" is a weasel word on line 92 at column 14
-------------
ral fields as wildcards, however ensure that you use no more than two wildcards 
                         ^^^^^^^
"however" is wordy or unneeded on line 92 at column 43
-------------
rge volume of data using several wildcards can trigger large scale searches, wit
                         ^^^^^^^
"several" is a weasel word on line 93 at column 47
-------------
ed if you are conducting several different searches. To address this, you can de
                         ^^^^^^^
"several" is a weasel word on line 96 at column 133
-------------
ant to delete The filter is highlighted, and the following options are displayed
                         ^^^^^^^^^^^^^^
"is highlighted" may be passive voice on line 100 at column 55
-------------
nd the following options are displayed:
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 100 at column 97
-------------
The filter is deleted.
           ^^^^^^^^^^
"is deleted" may be passive voice on line 111 at column 11
-------------
ves the Element, with no additional data. +
                         ^^^^^^^^^^
"additional" is wordy or unneeded on line 121 at column 31
-------------
The Element is stored locally while you work with it, and you can then apply you
            ^^^^^^^^^
"is stored" may be passive voice on line 122 at column 12
-------------
rieves the Element, with additional information highlighting any other elements 
                         ^^^^^^^^^^
"additional" is wordy or unneeded on line 125 at column 28
-------------
The Element is stored locally while it is worked on, before you then upload it b
            ^^^^^^^^^
"is stored" may be passive voice on line 126 at column 12
-------------
 is stored locally while it is worked on, before you then upload it back to the 
                         ^^^^^
"it is" is wordy or unneeded on line 126 at column 36
-------------
 stored locally while it is worked on, before you then upload it back to the mai
                         ^^^^^^^^^
"is worked" may be passive voice on line 126 at column 39
-------------
* Retrieve Multiple Elements +
           ^^^^^^^^
"Multiple" is wordy or unneeded on line 128 at column 11
-------------
Retrieves the several selected Elements, with no additional data. +
              ^^^^^^^
"several" is a weasel word on line 129 at column 14
-------------
lected Elements, with no additional data. +
                         ^^^^^^^^^^
"additional" is wordy or unneeded on line 129 at column 49
-------------
The Elements are stored locally while being worked on, before you then upload th
             ^^^^^^^^^^
"are stored" may be passive voice on line 130 at column 13
-------------
are stored locally while being worked on, before you then upload them back to th
                         ^^^^^^^^^^^^
"being worked" may be passive voice on line 130 at column 38
-------------
The Element is displayed in the panel, including related information, as follows
            ^^^^^^^^^^^^
"is displayed" may be passive voice on line 140 at column 12
-------------
ormation to determine if it is relevant or useful to you. +
                         ^^^^^
"it is" is wordy or unneeded on line 167 at column 51
-------------
You have successfully opened an element for inspection.
         ^^^^^^^^^^^^
"successfully" can weaken meaning on line 169 at column 9
-------------
NOTE: Elements are read-only in their native location. To edit an Element, perfo
               ^^^^^^^^
"are read" may be passive voice on line 171 at column 15
-------------
NOTE: Elements are read-only in their native location. To edit an Element, perfo
                        ^^^^
"only" can weaken meaning on line 171 at column 24
-------------
space. The data can then be edited as required.
                         ^^^^^^^^^
"be edited" may be passive voice on line 174 at column 106
-------------
owse or Retrieve Element are displayed.
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 179 at column 42
-------------
The Element is saved to your specified Workspace and is displayed in the panel, 
            ^^^^^^^^
"is saved" may be passive voice on line 181 at column 12
-------------
 specified Workspace and is displayed in the panel, including related informatio
                         ^^^^^^^^^^^^
"is displayed" may be passive voice on line 181 at column 53
-------------
You have successfully retrieved an element.
         ^^^^^^^^^^^^
"successfully" can weaken meaning on line 188 at column 9
-------------
The data is saved in your specified Workspace, and can be edited as required
         ^^^^^^^^
"is saved" may be passive voice on line 192 at column 9
-------------
ified Workspace, and can be edited as required
                         ^^^^^^^^^
"be edited" may be passive voice on line 192 at column 55
-------------
The following options are displayed:
                      ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 198 at column 22
-------------
The Element is saved to your specified Workspace, along with any dependencies.
            ^^^^^^^^
"is saved" may be passive voice on line 204 at column 12
-------------
lements and dependencies are displayed in the panel in separate tabs, as follows
                         ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 206 at column 30
-------------
You have successfully retrieved an element.
         ^^^^^^^^^^^^
"successfully" can weaken meaning on line 238 at column 9
-------------
NOTE: All dependencies are saved to the Workspace in appropriate folders based o
                       ^^^^^^^^^
"are saved" may be passive voice on line 240 at column 23
-------------
doesn't exist new folder is created +
                         ^^^^^^^^^^
"is created" may be passive voice on line 241 at column 65
-------------
atible with the Retrieve Multiple Elements action.
                         ^^^^^^^^
"Multiple" is wordy or unneeded on line 243 at column 71
-------------
==== Retrieve Multiple Elements
              ^^^^^^^^
"Multiple" is wordy or unneeded on line 245 at column 14
-------------
The Retrieve Multiple Elements action allows you to save a copy of several Eleme
             ^^^^^^^^
"Multiple" is wordy or unneeded on line 247 at column 13
-------------
ws you to save a copy of several Elements in a single action. The elements are s
                         ^^^^^^^
"several" is a weasel word on line 247 at column 67
-------------
gle action. The elements are saved without related metadata to your workspace, g
                         ^^^^^^^^^
"are saved" may be passive voice on line 247 at column 117
-------------
y Type. The elements can be used as required, and then merged back to the desire
                         ^^^^^^^
"be used" may be passive voice on line 247 at column 216
-------------
, you need to retrieve a multiple elements to your Workspace. This action allows
                         ^^^^^^^^
"multiple" is wordy or unneeded on line 249 at column 85
-------------
n allows you to retrieve several elements simultaneously, ensuring that you rece
                         ^^^^^^^
"several" is a weasel word on line 249 at column 157
-------------
the elements at the same point in time.
                         ^^^^^^^^^^^^^
"point in time" is wordy or unneeded on line 249 at column 267
-------------
ove up or down to select multiple elements that you want to retrieve
                         ^^^^^^^^
"multiple" is wordy or unneeded on line 259 at column 65
-------------
The Elements will be saved sequentially to your specified Workspace, sorted into
                  ^^^^^^^^
"be saved" may be passive voice on line 263 at column 18
-------------
The Elements are displayed as multiple separate tabs in the panel, including rel
             ^^^^^^^^^^^^^
"are displayed" may be passive voice on line 265 at column 13
-------------
lements are displayed as multiple separate tabs in the panel, including related 
                         ^^^^^^^^
"multiple" is wordy or unneeded on line 265 at column 30
-------------
You have successfully retrieved multiple elements and can now work with them in 
         ^^^^^^^^^^^^
"successfully" can weaken meaning on line 270 at column 9
-------------
e successfully retrieved multiple elements and can now work with them in Visual 
                         ^^^^^^^^
"multiple" is wordy or unneeded on line 270 at column 32
In src/main/pages/che-7/extensions/E4E-UsingE4E4VSC.adoc
=============
 support the creation of several Hosts in one instance.
                         ^^^^^^^
"several" is a weasel word on line 14 at column 116
-------------
 host per project or per time period, according to your needs.
                         ^^^^^^^^^^^
"time period" is wordy or unneeded on line 18 at column 37
-------------
* You can also have several hosts for one project which uses several data source
                    ^^^^^^^
"several" is a weasel word on line 19 at column 20
-------------
r one project which uses several data sources.
                         ^^^^^^^
"several" is a weasel word on line 19 at column 61
-------------
* Hosts can be renamed as their purpose changes. You can also update your creden
            ^^^^^^^^^^
"be renamed" may be passive voice on line 20 at column 12
-------------
ccess to the data source is maintained.
                         ^^^^^^^^^^^^^
"is maintained" may be passive voice on line 20 at column 122
-------------
View expands to show the several levels of Endevor data. You can use the path fo
                         ^^^^^^^
"several" is a weasel word on line 31 at column 29
-------------
ilters then allow you to only show the relevant information.
                         ^^^^
"only" can weaken meaning on line 31 at column 181
In src/main/pages/che-7/extensions/E4E-Views.adoc
=============
Filters are shown from the highest level first, with any subsequent related filt
        ^^^^^^^^^
"are shown" may be passive voice on line 8 at column 8
-------------
st level first, with any subsequent related filters showing as a drop-down optio
                         ^^^^^^^^^^
"subsequent" is wordy or unneeded on line 8 at column 57
-------------
Map View expands to show several levels of Endevor data. +
                         ^^^^^^^
"several" is a weasel word on line 12 at column 25
-------------
 shown, along with their subsequent sub-levels
                         ^^^^^^^^^^
"subsequent" is wordy or unneeded on line 13 at column 106
-------------
Filters are shown from the highest level first, with any subsequent related filt
        ^^^^^^^^^
"are shown" may be passive voice on line 19 at column 8
-------------
st level first, with any subsequent related filters showing as a drop-down optio
                         ^^^^^^^^^^
"subsequent" is wordy or unneeded on line 19 at column 57
-------------
** The top-level Filter is shown with the last two fields, Type and Element, as 
                        ^^^^^^^^
"is shown" may be passive voice on line 25 at column 24
-------------
*** The subsequent level shows the Type field specified, with only the Element f
        ^^^^^^^^^^
"subsequent" is wordy or unneeded on line 26 at column 8
-------------
pe field specified, with only the Element field as a wildcard.
                         ^^^^
"only" can weaken meaning on line 26 at column 62
-------------
This level contains only the elements that are reached by the specific path. As 
                    ^^^^
"only" can weaken meaning on line 28 at column 20
-------------
s only the elements that are reached by the specific path. As such no wildcards 
                         ^^^^^^^^^^^
"are reached" may be passive voice on line 28 at column 43
-------------
th. As such no wildcards are used here. +
                         ^^^^^^^^
"are used" may be passive voice on line 28 at column 98
-------------
of the same type, across several subsystems as the subsystem field is wildcarded
                         ^^^^^^^
"several" is a weasel word on line 47 at column 79
-------------
s as the subsystem field is wildcarded:
                         ^^^^^^^^^^^^^
"is wildcarded" may be passive voice on line 47 at column 121
-------------
of the same type, across several systems and their subsystems: +
                         ^^^^^^^
"several" is a weasel word on line 51 at column 82
-------------
es or specific data must be entered for every level when a filter is edited. +
                         ^^^^^^^^^^
"be entered" may be passive voice on line 55 at column 45
-------------
very level when a filter is edited. +
                         ^^^^^^^^^
"is edited" may be passive voice on line 55 at column 86
-------------
Filters View. You should therefore take care to delete redundant filters when no
                         ^^^^^^^^^
"therefore" is wordy or unneeded on line 57 at column 80
-------------
You can key several fields as wildcards, however you should aim to use no more t
            ^^^^^^^
"several" is a weasel word on line 58 at column 12
-------------
ral fields as wildcards, however you should aim to use no more than two wildcard
                         ^^^^^^^
"however" is wordy or unneeded on line 58 at column 41
-------------
rge volume of data using several wildcards can trigger large scale searches, wit
                         ^^^^^^^
"several" is a weasel word on line 58 at column 155
-------------
View expands to show the several levels of Endevor data as follows:
                         ^^^^^^^
"several" is a weasel word on line 62 at column 29
-------------
Each level in turn can be expanded to show its contents, until you reach the Ele
                       ^^^^^^^^^^^
"be expanded" may be passive voice on line 81 at column 23
-------------
dual pieces of data that are used by Endevor.
                         ^^^^^^^^
"are used" may be passive voice on line 81 at column 171
In src/main/pages/che-7/extensions/E4E-InstallE4EinVSC.adoc
=============
ance upgrade PTF SO08898 is included.
                         ^^^^^^^^^^^
"is included" may be passive voice on line 12 at column 49
-------------
es, to ensure everything is configured correctly prior to using Explorer for End
                         ^^^^^^^^^^^^^
"is configured" may be passive voice on line 29 at column 75
-------------
everything is configured correctly prior to using Explorer for Endevor for the f
                         ^^^^^^^^^
"correctly" can weaken meaning on line 29 at column 89
-------------
 is configured correctly prior to using Explorer for Endevor for the first time.
                         ^^^^^^^^
"prior to" is wordy or unneeded on line 29 at column 99
-------------
You have successfully installed the Explorer for Endevor extension for Visual St
         ^^^^^^^^^^^^
"successfully" can weaken meaning on line 31 at column 9
In src/main/pages/che-7/extensions/E4E-AdministratingE4E.adoc
=============
 the following resources prior to using Explorer for Endevor for the first time.
                         ^^^^^^^^
"prior to" is wordy or unneeded on line 3 at column 89
In src/main/pages/che-7/extensions/E4E-Messages.adoc
=============
 existing filter or make additional edits to create a unique filter.
                         ^^^^^^^^^^
"additional" is wordy or unneeded on line 12 at column 28
-------------
and so a new host cannot be named the same as any existing host
                         ^^^^^^^^
"be named" may be passive voice on line 41 at column 54
```

**Comment by themr0c** [comment]
Here are some asciidoc compliance hints by test-adoc.sh from https://github.com/jhradilek/check-links:

```
for file in `find  src/main/pages/che-7/extensions/ -name 'E4E-*.adoc'` ; do test-adoc.sh $file ; done

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-TPSA.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-Hosts.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-Accessibility.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module does not have any heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-ReleaseNotes.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-Actions.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-UsingE4E4VSC.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-Views.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-InstallE4EinVSC.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.
  [ FAIL ]  Module has more than one heading.

Checked 6 item(s) in 1 file(s), found 2 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-AdministratingE4E.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.

Checked 6 item(s) in 1 file(s), found 1 problem(s).

Testing file: /home/remote/ffloreth/src/gh/themr0c/che-docs/src/main/pages/che-7/extensions/E4E-Messages.adoc

  Document type: unknown

  [ FAIL ]  The file name does not use the con_, ref_, proc_, or assembly_ prefix.

Checked 6 item(s) in 1 file(s), found 1 problem(s).
```

**Comment by DStatWriter** [comment]
Hi all,

Having reviewed the above feedback, it does look generally stylistic. I am happy with the doc as it stands.

In terms of the 2nd tranche of feedback, is this a critical issue that would prevent publication? IF so can you advise with an example, the changes that i should make as the automated output of the tool doesn't make this clear.

Thanks,

Dan

**Comment by themr0c** [comment]
You are right, my comment is not useful if I don't provide a simple way to fix it.

For a conceptual overview, our framework is Modular Documentation. Here is the reference manual: https://redhat-documentation.github.io/modular-docs/. It is quite useful to read this document to decide what is the nature of the piece of documentation we want to write: an assembly, a concept, a reference or a procedure.

To make sure we have predictable quality, we have getting quite formal in the way each module is written. 

We delegate to a tool the task to add all the relevant attributes and formal bits to keep concentrated on the content. This tool is called `newdoc` and we use it to create any new file.  See https://github.com/redhat-documentation/tools/tree/master/newdoc 

And then, we have this tool to assess the compliance with our formal requirements:
test-adoc.sh from https://github.com/jhradilek/check-links.

We are not enforcing this formalism, at least for the moment, but we try to get in that direction as much as possible.

Is it something that you find useful?

**Comment by DStatWriter** [comment]
Thanks,

Are these Eclipse or Redhat standards, perhaps that is one and the same either formally or in practice?

I'm trying to learn the Eclipse Open source docs standards and use them to guide my writing going forwards.

In this particular instance, this product was originally not open source and so i am dealing with a lot of proprietary documents which would require a large overhead to convert them to the more formal structure at this stage.

I am certainly open to aligning to the required standards going forwards, as the project requires.

Thanks,

Dan

**Comment by themr0c** [comment]
All the Che documentation is currently far from compliant. It's a general direction we are heading to.

For the structure of the asciidoc documents, using the `newdoc` script and the `test-adoc.sh` validator is not a formal requirement. It is a daily practice that makes life easier. As a writer, thanks to these scripts, I don't have to worry about the generation of correct ids and metadata, I can stay focused on writing the content. I find them so useful that I believe it is a good idea to promote them and raise awareness that they are existing. Please tell me if I manage to convince you!

For the language, as Red Hat associates we are encouraged to apply "The IBM Style Guide" https://www.oreilly.com/library/view/the-ibm-style/9780132118989/. I don't know if the Eclipse Foundation is as prescriptive. I am personally interested in linters that would help writers have feedback.

**Comment by DStatWriter** [comment]
Closing due to change of doc strategy

**Comment by DStatWriter** [comment]
Re-opened as Explorer for Endevor is now Open-Sourced

**Comment by DStatWriter** [comment]
Closed as superceded

**Pull request closed without merging**
