### PR TITLE
Setting up Keycloak che-username-readonly-theme

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Add section to set up Keycloak che-username-readonly-theme

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/RHDEVDOCS-2453

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

screenshot-0 0 0 0_4000-2020 12 09-11_47_16

### CODE REVIEW

**Comment by MichalMaler** [comment]
Hello Anatolii. Nice work. Do you think you could send me the equivalent of those screenshots from CRW? Since there is the CHE branding, it will appear in the CRW docs after downstream. I will fix that but need those crw screenshots.

**Comment by tolusha** [comment]
It is committed in the PR 
`installation-guide/images/keycloak/keycloak_codeready_username_readonly_theme.png `

**Comment by MichalMaler** [comment]
Good job with those screenshots. Let me check it now.

**Review by MichalMaler — APPROVED** [review]

**Review by MichalMaler — COMMENTED** [review]
Need to fix the heading and create some intro.

**Review by MichalMaler — APPROVED** [review]

**Pull request merged**
