### PR TITLE
fix: removed devfile registry

### PR DESCRIPTION
**Pull request by deerskindoll**
## What does this pull request change?

removed mentions of devfile registry

## What issues does this pull request fix or reference?

https://github.com/eclipse-che/che/issues/23112

## Specify the version of the product this pull request applies to

main, 7.90.x

## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Comment by deerskindoll** [comment]
UPSTREAM ONLY: need to mention that  https://registry.devfile.io is a default registry right now

**Comment by deerskindoll** [comment]
@tolusha please check if this works for you, I can add more info to the upstream devfile registry page

**Comment by tolusha** [comment]
We have to remove the devfile registry from the image as well
https://66da3150f9a7e5a67bc2d5ac--eclipse-che-docs-pr.netlify.app/docs/next/administration-guide/server-components/

**Comment by svor** [comment]
here is an extra character: {Devfile Registry in https://github.com/eclipse-che/che-docs/blob/main/modules/end-user-guide/pages/devfile-introduction.adoc?plain=1#L24

**Review by svor — APPROVED** [review]
lgtm

**Review by svor — COMMENTED** [review]
@deerskindoll this image should be updated as well https://66db1417b00b1b9b92d31f2a--eclipse-che-docs-pr.netlify.app/docs/next/administration-guide/gateway/

please remove Devfile registry

**Comment by deerskindoll** [comment]
> @deerskindoll this image should be updated as well https://66db1417b00b1b9b92d31f2a--eclipse-che-docs-pr.netlify.app/docs/next/administration-guide/gateway/
> 
> please remove Devfile registry

I removed devfile registry from all diagrams

**Review by svor — APPROVED** [review]
lgtm

**Pull request merged**
