### PR TITLE
Update Release Notes template

### PR DESCRIPTION
**Pull request by dneary**
Updated Release Notes template to include boilerplate we use for the recurring blog post.

Release notes will be collected here after publication of the blog posts in the future.

### What does this PR do?

Update release notes template to include boilerplate we have been using for Che release notes blog posts

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by dneary** [comment]
Who has write access to che-docs? As an Eclipse committer, should I have it?

**Comment by slemeur** [comment]
You should I think.

**Review by slemeur — APPROVED** [review]

**Comment by dneary** [comment]
I do not have a "Merge pull request" button.

**Comment by dneary** [comment]
Turns out I had missed an organization inviotation. Fixed now. Merging,

**Pull request merged**
