### PR TITLE
fix: annotations typo in CheCluster example

### PR DESCRIPTION
**Pull request by dkwon17**
## What does this pull request change?
Fixes typo in the field name

## Specify the version of the product this pull request applies to
 Che 7.88, DS 3.15
 
## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [x] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
- [x] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Review by deerskindoll — APPROVED** [review]
lgtm

**Comment by dkwon17** [comment]
Thank you for the review @deerskindoll , can I merge this PR?

**Comment by deerskindoll** [comment]
> Thank you for the review @deerskindoll , can I merge this PR?

sure, go ahead! can you please cherry-pick it as well while you're at it?

**Comment by dkwon17** [comment]
There was another small typo, I just fixed it.

> cherry-pick it as well while you're at it?

Sounds good, I will cherry pick it too

**Pull request merged**
