### PR TITLE
Move "Customizing the registries" to the Contributor guide

### LINKED ISSUE #17510: [Docs] Fix instructions for build plug-in and devfile registries
### Is your enhancement related to a problem? Please describe.

The [docs](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/) describing how to build a new version of the plug-in and devfile registries instruct the user to run `docker build -t my-registry image .`.    The two repositories now rely on a build script.

### Describe the solution you'd like

The documentation should be changed to reflect how these images are currently built, using their respective build scripts.

### PR DESCRIPTION
**Pull request by themr0c**
* Move "Customizing the registries" to the Contributor guide
* Move "Editing a devfile and plug-in at runtime", "Adding a VSCode extension" and "Publishing a VS Code extension" to the End-user Guide
* Modularize "Customizing the registries", reusing "Building offline images"
* Follow conventions for file names

fixes: https://github.com/eclipse/che/issues/17510

### PR Checklist

As the author of this Pull Request I made sure that:

- [x] `vale` has been run successfully against the PR branch
- [x] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Comment by themr0c** [comment]
Screenshot from 2020-10-09 13-12-29

Screenshot from 2020-10-09 13-12-48

Screenshot from 2020-10-09 13-12-56


Screenshot from 2020-10-09 13-13-05

Screenshot from 2020-10-09 13-11-51

**Comment by themr0c** [comment]
Vale: improvements but not fixed everything.

**Comment by rkratky** [comment]
@themr0c, this looks good (based on the screenshots), but one nitpick: let's unify the headings with what's in the navig menu.

**Comment by themr0c** [comment]
Screenshot from 2020-10-09 15-49-50
Screenshot from 2020-10-09 15-50-00

**Review by rkratky — APPROVED** [review]

**Pull request merged**
