### PR TITLE
update namespace strategies with new CHE_INFRA_KUBERNETES_NAMESPACE v…

### PR DESCRIPTION
**Pull request by sparkoo**
…ariable and <workspaceid> placeholder

Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
Updates workspace namespaces strategies docs. In this PR https://github.com/eclipse/che/pull/14828, the `che.infra.kubernetes.namespace` and `che.infra.openshift.project` will became obsolete and are replaced with `che.infra.kubernetes.namespace.default`. This PR updates the docs.
Also There is new `<workspaceid>` placeholder. This effectively replaces the default empty value resolving to workspace id.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14585

### CODE REVIEW

**Review by rkratky — CHANGES_REQUESTED** [review]
@sparkoo, I fixed a few thinks but then realized that I needed to edit the sidebar YAML to include the content in the navig. menu. So, I submitted the rest as a PR against your feature branch at https://github.com/sparkoo/che-docs/pull/2

**Comment by sparkoo** [comment]
@rkratky great, thanks. I've merged that to the branch.

**Comment by sparkoo** [comment]
Please don NOT merge this! It's documenting changes from PR https://github.com/eclipse/che/pull/14828 so we need to merge that one first, then the docs.

**Comment by rkratky** [comment]
@sparkoo, sure, please, let me know you're ready.

**Review by metlos — APPROVED** [review]

**Review by rkratky — APPROVED** [review]

**Comment by sparkoo** [comment]
@rkratky the code PR was merged. We're good to go with this one.

**Comment by rkratky** [comment]
@sparkoo, thanks. Merged.

**Pull request merged**
