### PR TITLE
Anatoly's feedback

### PR DESCRIPTION
**Pull request by MichalMaler**
Signed-off-by: Michal Maléř <mmaler@redhat.com>

### CODE REVIEW

**Comment by MichalMaler** [comment]
@tolusha Anatoly :) Please, check and approve. Thank you!

**Review by tolusha — APPROVED** [review]

**Review by tolusha — CHANGES_REQUESTED** [review]
Why do we need these changes for upstream? 
It is about restricted env.

**Comment by MichalMaler** [comment]
well, it is part of modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool.adoc
which is for CHE/CRW (writing this for Che then downstreamed to CRW)

And from the restricted environment chapter in CRW, we are pointing to this file. To make changes in that file, we modify the upstream equivalent. That's why we came out with that new attribute.

**Comment by MichalMaler** [comment]
closing this since there is a better solution

**Pull request closed without merging**
