### PR TITLE
Eclipse Che4z GA documentation update

### PR DESCRIPTION
**Pull request by zeibura**
### What does this PR do?
Eclipse Che4z is now full GA and the GA release is slightly different from the Beta release. The stack now contains LSP for COBOL and Explorer for Endevor along with Zowe Explorer and several Zowe CLI plugins.
Accordingly all z/OS Resource Explorer documentation has been removed, and the Product Accessibility Features page has also been removed as it has been deemed quite pointless.
More topics will be added to the documentation soon - Explorer for Endevor is about to be made open source so in a few weeks time we will add the user guide for that.

### What issues does this PR fix or reference?
#15165

### CODE REVIEW

**Comment by zeibura** [comment]
Could this be looked at today if possible please? We went GA with this yesterday and would like the documentation out asap. Thank you

**Comment by slemeur** [comment]
cc @rkratky and @themr0c

**Review by rkratky — CHANGES_REQUESTED** [review]
@zeibura, I submitted a PR with suggested fixers against your topic branch. Find it at https://github.com/zeibura/che-docs/pull/3

**Comment by zeibura** [comment]
I think I accepted the changes but it's still saying changes requested...

**Review by slemeur — APPROVED** [review]

**Review by rkratky — APPROVED** [review]
Thanks, @zeibura. Merging.

**Pull request merged**
