### PR TITLE
Deprecate namespace strategies other than 'per user'

### PR DESCRIPTION
**Pull request by skabashnyuk**
> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Provide additional information about deprecation of namespace strategies other than 'per user'

### What issues does this PR fix or reference?
Related to https://github.com/eclipse/che/issues/19365 and  https://github.com/eclipse/che/pull/19409

### Specify the version of the product this PR applies to.
7.29

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [ ] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by sparkoo — APPROVED** [review]

**Review by tolusha — APPROVED** [review]

**Comment by MichalMaler** [comment]
Hello @skabashnyuk. Thank you for the contribution.
Why is this content an assembly? It looks more like a proc/concept module to me (based on how this will be rewritten). Are you planning to add more procedure/concept modules into this in the future?

Just for clarification:
Assembly - A collection of several procedures or concept modules
Procedure - Steps how to do something (prerequisites + steps)
Concept - Telling a user how things work (short summarization of some knowhow)

**Comment by sparkoo** [comment]
Not related to this PR

> 
> Just for clarification:
> Assembly - A collection of several procedures or concept modules
> Procedure - Steps how to do something (prerequisites + steps)
> Concept - Telling a user how things work (short summarization of some knowhow)

@MichalMaler This is gold, can you please write it to the main README or CONTRIBUTING.md ?

**Comment by skabashnyuk** [comment]
@MichalMaler I've made this page similar to `upgrading-che-using-operatorhub.adoc`. I had no special intention underneath. Want me to change it to `Procedure`?

**Comment by yhontyk** [comment]
@skabashnyuk I've submitted a PR against your branch https://github.com/skabashnyuk/che-docs/pull/3 with some suggestions on the structure and the language.

@sparkoo we do have this mentioned (although very briefly :( )

>Guidelines from the Modular Documentation Initiative. As Antora is using the term of module with a different meaning, this project is referring to modules as topics. To understand the nature of topics, see the Appendix A: Modular Documentation Terms and Definitions.

I'll update the Contribution guide. Thanks for the suggestion.

**Comment by skabashnyuk** [comment]
@boczkowska your pr has been merged. Thank you

**Pull request merged**
