### PR TITLE
chore: Avoid Base64 encoding steps in documentation

### PR DESCRIPTION
**Pull request by tolusha**
## What does this pull request change?
chore: Avoid Base64 encoding steps in documentation

## What issues does this pull request fix or reference?
https://github.com/eclipse/che/issues/22489

## Specify the version of the product this pull request applies to
 main
 
## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [x] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Review by deerskindoll — APPROVED** [review]
lgtm

**Review by ibuziuk — COMMENTED** [review]
Really good improvement, just wondering if the procedure has been verified? e.g. `$HOME/.docker/config.json`

**Comment by tolusha** [comment]
@ibuziuk 
I've verified only changes related to configuration OAuth 1.0 for BitBucker server.

**Review by vinokurig — APPROVED** [review]

**Comment by tolusha** [comment]
@ibuziuk 
I came to the conclusion that it is needed to revert some changes.
Specifically where we suggest putting non encoded json content into a Secret.
If data contains a leading tab character then creating the Kubernetes Secret will fail:

`error: error parsing STDIN: error converting YAML to JSON: yaml: line 8: found a tab character where an indentation space is expected
`

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
