### PR TITLE
fix: update resource limits for developer sandbox

### PR DESCRIPTION
**Pull request by cedricclyburn**
## What does this pull request change?

This PR changes resource limits for Developer Sandbox accounts @ https://developers.redhat.com/developer-sandbox/FAQ

## What issues does this pull request fix or reference?

N/A

## Specify the version of the product this pull request applies to

Latest

## Pull Request checklist

The author and the reviewers validate the content of this pull request with the following checklist, in addition to the [automated tests](code_review_checklist.adoc).

- Any procedure:
  - [ ] Successfully tested.
- Any page or link rename:
  - [ ] The page contains a redirection for the previous URL.
  - Propagate the URL change in:
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts)
- [ ] Builds on [Eclipse Che hosted by Red Hat](https://workspaces.openshift.com).
- [ ] the *`Validate language on files added or modified`* step reports no vale warnings.

### CODE REVIEW

**Comment by cedricclyburn** [comment]
I just signed the ECA, sorry about that.

**Review by deerskindoll — APPROVED** [review]
lgtm

**Review by ibuziuk — APPROVED** [review]

**Comment by ibuziuk** [comment]
@cedricclyburn thank you for the contribution
Please, sign Eclipse Contributor Agreement(ECA) - https://www.eclipse.org/legal/ECA.php 
once done PR check should be green, and we will be able to merge

**Comment by cedricclyburn** [comment]
Gotcha @ibuziuk sorry about that, all good now!

**Comment by ibuziuk** [comment]
@deerskindoll could you please trigger the PR check and merge

**Comment by ibuziuk** [comment]
@cedricclyburn it looks like the PR check is stuck :/
could you please rebase the PR on top main?

**Comment by cedricclyburn** [comment]
Gotcha @ibuziuk I have merged main into my changes

**Comment by ibuziuk** [comment]
@deerskindoll could you please follow up and merge the PR?

**Comment by deerskindoll** [comment]
> @deerskindoll could you please follow up and merge the PR?

sure!

**Comment by deerskindoll** [comment]
@cedricclyburn can you please cherry-pick the commit from this PR? https://github.com/eclipse-che/che-docs/pull/2703

here's the SHA: 86a1883

it should fix the failing pipeline

**Comment by ibuziuk** [comment]
@cedricclyburn sorry for the hassle, but could you please try simply rebasing on the main
I do not think cherry-picking commits is required

**Comment by ibuziuk** [comment]
@deerskindoll please, close and open relevant PR with the same changes against main

**Comment by deerskindoll** [comment]
> @deerskindoll please, close and open relevant PR with the same changes against main

here you go: https://github.com/eclipse-che/che-docs/pull/2723

**Pull request closed without merging**
