### PR TITLE
Configure labels and domains to work with router sharding

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Configure labels and domains to work with router sharding

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1466

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

screenshot-0 0 0 0_4000-2021 03 05-11_53_41

### CODE REVIEW

**Comment by yhontyk** [comment]
@tolusha hi! could you take a look at it again if there wasn't a mistake with renames/removals of the files?

You have renamed xrefs from `configuring-labels-for-routes.adoc` to `configuring-labels-and-domains-for-routes.adoc` but haven't added the actual `configuring-labels-and-domains-for-routes.adoc` file (and removed the old one).

**Comment by tolusha** [comment]
@boczkowska 
I've committed missing files.

**Review by yhontyk — APPROVED** [review]

**Comment by tolusha** [comment]
@boczkowska 
linkcheckers failed ^(

**Comment by tolusha** [comment]
@boczkowska 
can we merge this?

**Comment by tolusha** [comment]
@skabashnyuk
could you review it pls ?

**Review by MichalMaler — APPROVED** [review]

**Pull request merged**
