### PR TITLE
Tell how to generate an SSH Key

### PR DESCRIPTION
**Pull request by RickJWagner**
### Specify the version of the product this PR applies to.

### CODE REVIEW

**Review by yhontyk — APPROVED** [review]

**Comment by yhontyk** [comment]
Hi @RickJWagner! Thank you for the PR. LGTM could you sign off your commit?

Run `git commit --amend`, add `Signed-off-by: Rick Wagner <rwagner@redhat.com>` to the commit message and then force push `git push -f`.

Thank you!

**Comment by RickJWagner** [comment]
git commit --amend

**Comment by RickJWagner** [comment]
Signed-off-by: Rick Wagner <rwagner@redhat.com>

**Comment by RickJWagner** [comment]
git push -f

**Comment by RickJWagner** [comment]
git commit -a -s

**Comment by RickJWagner** [comment]
Closing, I have re-created the request with a signed commit.

**Comment by MichalMaler** [comment]
Tweak in https://github.com/eclipse/che-docs/pull/1152
Good job, @RickJWagner  ! :+1:

**Pull request closed without merging**
