### PR TITLE
feat(plugin-registry): Handle new changes in plugin registry

### PR DESCRIPTION
**Pull request by benoitf**
> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

- [x] : need to be merged after https://github.com/eclipse/che-plugin-registry/pull/815 is merged

### What does this PR do?
Keep in sync changes done as part of https://github.com/eclipse/che-plugin-registry/pull/815

### What issues does this PR fix or reference?
https://github.com/eclipse/che-plugin-registry/pull/815

### Specify the version of the product this PR applies to.

7.26

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [x] Link checker has been run successfully against the PR branch
- [x] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [x] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [x] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [x] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

Change-Id: I76d0f115bd82bc40cc1c6f6a34e776ab92876776
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by yhontyk — APPROVED** [review]
Approving. Merge when ready,

**Comment by themr0c** [comment]
@benoitf Is this PR ready from your standpoint?
@ericwill We are waiting for your review.

**Comment by benoitf** [comment]
@themr0c yes 👍

**Comment by themr0c** [comment]
We need to wait for the release of 7.26 before merging.

**Review by ericwill — APPROVED** [review]
Sorry, I thought I approved this already. Changes are fine by me :+1:

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
https://github.com/eclipse/che/releases/tag/7.26.0 is out, we can merge this PR

**Pull request merged**
