### PR TITLE
fix: Corrected a typo in url of role_binding.yaml

### PR DESCRIPTION
**Pull request by KateSieraia**
> Read our [Contribution guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) before submitting a PR.

### What does this PR do?
Corrected a typo

### What issues does this PR fix or reference?
Link used to lead to 404 page, now it works

### Specify the version of the product this PR applies to.
7

### PR Checklist

As the author of this Pull Request I made sure that:

- [ ] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been configured on the docs side):
    - [ ] Dashboard [default branding data](https://github.com/eclipse-che/che-dashboard/blob/main/src/services/bootstrap/branding.constant.ts)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by MichalMaler — APPROVED** [review]

**Review by themr0c — APPROVED** [review]
Nice spot, thank you!

**Comment by themr0c** [comment]
@KateSieraia Your commit is failing the eclipsefdn/eca  validation, because the private email address used is not the email address you used to sign the ECA.  See: https://accounts.eclipse.org/legal/eca/validation/70436

To fix it, you need to amend the commit to fix the email address. Please tell us if this procedure is something you can do easily.

It's a  common problem  when committing using GitHub web UI, and the user has set a general "Keep my email addresses private". 

Workaround for later commits: disable the general "Keep my email addresses private" in  https://github.com/settings/emails , and in eclipse repositories,

**Comment by MichalMaler** [comment]
Yep, @KateSieraia.

The addition of your signature can be done using:

1) git pull
2) git commit --amend -s
3) git push -f

**Comment by KateSieraia** [comment]
@themr0c @MichalMaler thank you for your tips and sorry for inconvenience, hopefully I will be able to fix it by the end of the day

**Comment by KateSieraia** [comment]
@themr0c @MichalMaler looks like it worked :)

**Pull request merged**
