### PR TITLE
I1669 missing orientation headers

### PR DESCRIPTION
**Pull request by MichalMaler**
Signed-off-by: Michal Maléř mmaler@redhat.com

* Adding orientation handles (mother assembly context information) and :page-liquid: attribute when needed
* Fixing context information of all AG files
* Cleaning the AG section from unused or empty template files
* Removing `che-plugin-broker` and replacing it for NOTE mention (mention in left bar menu has been deleted)
* Fixing broken link

### CODE REVIEW

**Comment by yhontyk** [comment]
Why did you remove all `// Module/Assembly included in the following assemblies:` lines?

Please rebase and solve conflicts. Let me know if you need any help with that.

**Comment by MichalMaler** [comment]
Hey, I simply did it because of the consistency with already existing docs, which were in the majority. This method is also applied in the platform docs. The next thing was that in most cases, there was used  `assembly_name.adoc` format -> which you don't need to know honestly since those handles are used for easier xrefs (or sometimes links creation), so you are provided with the info you don't really need.

Providing only the `context` information without any more lines and comments sounded like a good idea to me.

**Review by rkratky — CHANGES_REQUESTED** [review]
@MichalMaler, when building, it throws the following error:
```
asciidoctor: ERROR: ref_configuring-system-variables.adoc: line 16: include file not found: /che-docs/pages/che-7/administration-guide/examples/system-variables.adoc
```
Please, fix it (and the conflicts the PR has), and it can be merged.

**Comment by yhontyk** [comment]
@rkratky regarding system variable file https://github.com/eclipse/che-docs/pull/1046#issuecomment-586869514

**Comment by yhontyk** [comment]
@rkratky please, in the future, assign yourself as the reviewer of the PR the moment you start to review it, so nobody does the double work.

**Comment by MichalMaler** [comment]
@rkratky Hi,none error in my build, though.
image

Maybe you have an old version where my fix of that problem wasn't involved. I fixed that script 2 days ago. https://issues.redhat.com/browse/RHDEVDOCS-1682

And I also know that if there is a conflict, I have to fix it.

**Comment by MichalMaler** [comment]
Fixed and ready

**Comment by rkratky** [comment]
> Maybe you have an old version where my fix of that problem wasn't involved. I fixed that script 2 days ago.

Nope, I checked out directly your PR. Just to make sure, I have now also checked out your branch (`i1669-missing-orientation-headers`) directly, and I'm still getting the same error.

You can see for yourself that the referenced file does not exist in your PR branch:
https://github.com/MichalMaler/che-docs/tree/i1669-missing-orientation-headers/src/main/pages/che-7/administration-guide/examples
(there's no `system-variables.adoc` in that directory).

(The file does not exist in the current `master` either  even though it is referenced from `ref_configuring-system-variables.adoc`, so I'm not sure where you fixed it. See https://github.com/eclipse/che-docs/tree/master/src/main/pages/che-7/administration-guide/examples and https://raw.githubusercontent.com/eclipse/che-docs/master/src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc)

**Comment by themr0c** [comment]
The missing `ref_configuring-system-variables.adoc` is the file which is generated by a script. It's  known issue.

**Comment by rkratky** [comment]
Thanks, @themr0c. I can't find an issue filed for this. Let's discuss elsewhere.

**Review by rkratky — APPROVED** [review]

**Pull request merged**
