### PR TITLE
Fix language in end-user-guide

### PR DESCRIPTION
**Pull request by themr0c**
Fix language on:
* assembly_accessing-che-from-openshift-developer-perspective.adoc 
* assembly_using-go-artifact-repositories.adoc 
* proc_importing-certificates-to-browsers.adoc 
* proc_using-jetbrains-intellij-idea-community-edition.adoc 
* proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
* proc_writing-a-devfile-for-your-project.adoc 

### PR Checklist

As the author of this Pull Request I made sure that:

- [x] `vale` has been run successfully against the PR branch
- [ ] Link checker has been run successfully against the PR branch
- [ ] Documentation describes a scenario that is already covered by QE tests, otherwise an issue has been created and acknowledged by Che QE team
- [ ] Changed article references are updated where they are used (or a redirect has been set up on the docs side):
    - [ ] Dashboard [branding.json](https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.json)
    - [ ] Chectl [constants.ts](https://github.com/che-incubator/chectl/blob/master/src/constants.ts)

### CODE REVIEW

**Review by MichalMaler — APPROVED** [review]

**Comment by yhontyk** [comment]
```
 62:94   error       Avoid using 'operator'.         Vale.Avoid       
 62:94   error       Use 'Operator' instead of       Vale.Terms       
                     'operator'.     
                     
```
@themr0c 
1. Can you remove this rule from Vale.Avoid? So we don't have the duplication.
2. ...and update the Vale.Terms with proper regex? (`operator` should only be reported as an error if it's a seperate word, probably smth like `(^| )operator` can work)

**Comment by themr0c** [comment]
@boczkowska yes that's in the pipe.

**Comment by themr0c** [comment]
From 89 errors to:

```
vale --minAlertLevel=error modules/end-user-guide/
 modules/end-user-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
 60:43  error  Avoid using 'item'.  Vale.Avoid 
 modules/end-user-guide/examples/che-ref_annotations-description.adoc
 7:36  error  Avoid using 'item'.  Vale.Avoid 
✖ 2 errors, 0 warnings and 0 suggestions in 229 files.
``

**Review by yhontyk — APPROVED** [review]
Approving. Merge when ready. :relaxed:

**Comment by themr0c** [comment]
0 errors target reached (on the laptop).

**Comment by themr0c** [comment]
Fixing 89 vale errors on the user guide and focusing on false positives paid:

Before: https://github.com/eclipse/che-docs/runs/2227076179?check_suite_focus=true - 700 vale errors on master.
After: https://github.com/eclipse/che-docs/runs/2238169583?check_suite_focus=true - 427 vale errors on master.

**Pull request merged**
