### PR TITLE
Pr 1265

### PR DESCRIPTION
**Pull request by rkratky**
### What does this PR do?

Rearchitecture quick starts. Based mainly on #1265 -- thanks a lot for that work, @adriendelsalle!

### CODE REVIEW

**Review by themr0c — APPROVED** [review]

**Comment by adriendelsalle** [comment]
Hi @rkratky , you're welcome.

I don't totally understand why you submitted a [PR on my fork](https://github.com/adriendelsalle/che-docs/pull/1) and then decide to submit your own PR here before discussing about the [few points I disagree](https://github.com/adriendelsalle/che-docs/pull/1#pullrequestreview-435256522). This is *not* very collaborative, I hope you will consider those.

@themr0c, I'm not sure you should have validated this PR since mine was already open and under review, ihmo you should have reacted on the existing thread.

@l0rd, you started reviewing my PR, please also give your opinion as a maintainer on this process.

Thanks

**Comment by themr0c** [comment]
@adriendelsalle It's mainly because we wanted to see all of your work integrated before shuffling everything around with the Antora migration!

**Comment by adriendelsalle** [comment]
Hi! Ohh that's ok then. Good luck for that work!
I was just a bit frustrated to wait few weeks (and that's totally ok we all have a lot to do) to see it merged and then not have the opportunity to discuss few points before merging.

I will propose some small adjustments in another PR, it will be maybe easier to review compared to this one.

**Comment by themr0c** [comment]
I can understand. After migration to Antora, we would like to move into the Installation Guide most parts of the Overview that are related to the installation, and keep only pointers to the Installation Guide. Should I ping you on that topic then?

(One of the rationale is to keep as much as possible xrefs pointing to the same guide, I believe that a high level of cross-guide references is a good indicator of a misplacement of some chapters and sections)

**Comment by themr0c** [comment]
@adriendelsalle also note that https://github.com/eclipse/che-docs/pull/1324 was built on top of your contrib ;).

**Comment by adriendelsalle** [comment]
It will be my pleasure @themr0c!
You're right it's a bit strange to have all these procs not part of the installation guide, mainly focussing on configuring Che.

**Comment by adriendelsalle** [comment]
> @adriendelsalle also note that #1324 was built on top of your contrib ;).

It was clearly not my purpose. Thanks again !

**Pull request merged**
