### PR TITLE
Add Che4z content

### PR DESCRIPTION
**Pull request by zeibura**
Added Che4z content - four pages and updated the yml sidebar

Signed-off-by: Zeibura Kathau <zeibura.kathau@broadcom.com>

What does this PR do?
This is all the content required for the Che4z release - four new pages plus the sidebar update.

What issues does this PR fix or reference?
#14395

### CODE REVIEW

**Comment by slemeur** [comment]
This looks pretty nice to me.

**Review by slemeur — APPROVED** [review]

**Comment by themr0c** [comment]
@zeibura I have fixed the merge conflicts for you and fixed the navigation.

@rkratky Can you please review and tell me if we can merge this contribution as is.

**Review by rkratky — APPROVED** [review]
Thanks, @themr0c

**Comment by themr0c** [comment]
fix https://github.com/eclipse/che/issues/14395

**Pull request merged**
