### PR TITLE
generate name docs

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
document generate name

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15020

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by sparkoo** [comment]
@rkratky @themr0c please review

**Review by rkratky — CHANGES_REQUESTED** [review]
@sparkoo, changes suggested in https://github.com/sparkoo/che-docs/pull/3

**Comment by sparkoo** [comment]
@rkratky your changes are ok but one small thing. For factory, the `generateName` is used when both are defined. I've added that to the note (https://github.com/eclipse/che-docs/pull/892/commits/538722939d019ebb214fd9badf772386aee8c3a8). Please check.

**Review by rkratky — APPROVED** [review]

**Comment by rkratky** [comment]
Thanks, @sparkoo

**Pull request merged**
